chmod +x scripts/requirements1.sh
chmod +x scripts/requirements2.sh
chmod +x scripts/deployAll.sh
chmod +x scripts/cleanCluster.sh
chmod +x scripts/uninstall.sh
chmod +x scripts/deployApp.sh
chmod +x scripts/deployKafka.sh
chmod +x scripts/deployPrometheus.sh
chmod +x scripts/LaunchTestFromScratch.sh
chmod +x scripts/verifyIfOnePodLatency.sh
chmod +x scripts/cleanPrometheus.sh
chmod +x scripts/cleanElastic.sh