---
- name: Deploy Prometheus and Grafana
  hosts: localhost

  tasks:
    - name: Add the Prometheus Chart Repository
      kubernetes.core.helm_repository:
        name: prometheus-community
        repo_url: "https://prometheus-community.github.io/helm-charts"

    - name: Apply Prometheus and Grafana
      kubernetes.core.helm:
        name: prometheus
        chart_ref: prometheus-community/kube-prometheus-stack
        release_namespace: default
        values_files:
          - ../kubernetes/prometheus-values.yaml