---
- name: Deploy Elastic Stack
  hosts: localhost

  tasks:
    - name: Add helm elastic repo
      command: helm repo add elastic https://helm.elastic.co

    - name: Update helm repo
      command: helm repo update

    - name: Install elastic operator
      command: helm install elastic-operator elastic/eck-operator -n elastic-system --create-namespace

    - name: Creat elastic namespace
      command: kubectl create namespace elastic

    - name: Apply Elastic Priority Classes
      command: kubectl apply -f ../elastic-stack/elastic-priority-classes.yaml

    - name: Apply Elasticksearch cluster
      command: kubectl apply -f ../elastic-stack/elasticsearch-cluster.yaml
     
    - name: Apply Kibana instance
      command: kubectl apply -f ../elastic-stack/kibana-instance.yaml

    - name: Apply Filebeat
      command: kubectl apply -f ../elastic-stack/filebeat-kubernetes.yaml
      
    - name: Get password before command kubectl apply -f filebeat-kubernetes.yaml
      command: kubectl get secret elastic-cluster-es-elastic-user -o go-template='{{.data.elastic | base64decode}}' -n elastic

