---
- name: Deploy Kafka Cluster
  hosts: localhost

  tasks:
    - name: Apply Strimzi Ressources
      command: kubectl apply -f https://strimzi.io/install/latest?namespace=default

    - name: Apply Kafka (metrics3.yaml)
      command: kubectl apply -f ../kubernetes/metrics3.yaml

    - name: Apply Kafka Topic
      command: kubectl apply -f ../kubernetes/kafka-topic.yaml
