---
- name: Deploy Prometheus, Grafana, and related resources
  hosts: localhost
  tasks:
    - name: Apply Prometheus Operator Deployment
      command: kubectl create -f ../kubernetes/prometheus-operator-deployment.yaml

    - name: Apply Prometheus Additional Configuration
      command: kubectl create -f ../kubernetes/prometheus-additional.yaml

    - name: Apply Prometheus Rules
      command: kubectl create -f ../kubernetes/prometheus-rules.yaml

    - name: Apply Strimzi Pod Monitor
      command: kubectl create -f ../kubernetes/strimzi-pod-monitor.yaml

    - name: Apply Prometheus Configuration
      command: kubectl create -f ../kubernetes/prometheus.yaml

    - name: Apply Grafana Configuration
      command: kubectl create -f ../kubernetes/grafana.yaml

    - name: Apply Prometheus Service
      command: kubectl create -f ../kubernetes/prometheus-service.yaml