---
- name: Deploy Prometheus and Grafana
  hosts: localhost

  tasks:
    - name: Apply Prometheus Operator Deployment
      command: kubectl apply -f prometheus-operator-deployment.yaml

    - name: Apply Prometheus Additional Configuration
      command: kubectl apply -f prometheus-additional.yaml

    - name: Apply Prometheus Rules
      command: kubectl apply -f prometheus-rules.yaml

    - name: Apply Strimzi Pod Monitor
      command: kubectl apply -f strimzi-pod-monitor.yaml

    - name: Apply Prometheus Configuration
      command: kubectl apply -f prometheus.yaml

    - name: Apply Grafana Configuration
      command: kubectl apply -f grafana.yaml